description: "Валюты"
get:
    description: |
        Возвращает список валют

        Для вывода всего списка пишем: `per-page=9999999`
    is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/is/get-list.raml
    responses:
        200:
            body:
                application/json:
                    #type: !include schema/list.json
                    example: !include example/list.json
post:
    securedBy: [TPSAuth]
    description: "Создать валюту"
    is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/is/post.raml
    body:
        application/json:
            #type: !include schema/add.json
            example: !include example/add.json

/{id}:
    uriParameters:
        id:
            description: "ID валюты"
            type: integer
    get:
        description: "Возвращает валюту"
        is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/is/get-details.raml
        responses:
            200:
                body:
                    application/json:
                        #type: !include schema/details.json
                        example: !include example/details.json
    put:
        securedBy: [TPSAuth]
        description: "Изменить валюту"
        is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/is/put.raml
        body:
            application/json:
                #type: !include schema/edit.json
                example: !include example/edit.json
    delete:
        securedBy: [TPSAuth]
        description: "Удалить валюту"
        is: !include /../../../vendor/yii2lab/yii2-rest/src/domain/docs/is/delete.raml
